### ISSUE TITLE
Redirect tracking

### ISSUE THREAD

**Issue by jaredhasenklein** [jaredhasenklein/Resource-Hub#18]
**Tracking of needed redirects per #11**

**Comment by jaredhasenklein** [comment]
The checkboxes inside the table aren't working right. Tracking here now:

# FLL 
- [x] https://hub.jaredhk.com/sites/fll2015.html -> https://hub.jaredhk.com/sites/fll/2015.html
- [x] http://fll16.jaredhk.com/ -> https://hub.jaredhk.com/sites/fll/2016.html
- [x] http://fll17.jaredhk.com/ -> https://hub.jaredhk.com/sites/fll/2017.html
- [x] http://fll18.jaredhk.com/ -> https://hub.jaredhk.com/sites/fll/2018.html

# FTC
- [x] https://hub.jaredhk.com/sites/ftc2016.html -> https://hub.jaredhk.com/sites/ftc/2016.html

# FRC 
- [x] https://hub.jaredhk.com/sites/frc2016.html -> https://hub.jaredhk.com/sites/frc/2016.html
- [x] https://hub.jaredhk.com/sites/frc2017.html -> https://hub.jaredhk.com/sites/frc/2017.html
- [x] https://frc18.jaredhk.com/ -> https://hub.jaredhk.com/sites/frc/2018.html
- [x] https://deepspace.jaredhk.com/ -> https://hub.jaredhk.com/sites/frc/2019.html
- [x] https://frc19.jaredhk.com/ -> https://hub.jaredhk.com/sites/frc/2019.html

# VRC 
- [x] https://hub.jaredhk.com/sites/vex2016.html -> https://hub.jaredhk.com/sites/vrc/2016.html

# Pickers
- [x] https://hub.jaredhk.com/vex.html -> index.html
- [x] https://hub.jaredhk.com/fll.html -> index.html
- [x] https://hub.jaredhk.com/ftc.html -> index.html
- [x] https://hub.jaredhk.com/frc.html -> index.html

# Individuals 
- [x] https://hub.jaredhk.com/sites/space/firstinspace.html -> index.html
- [x] https://hub.jaredhk.com/diversity.html -> https://hub.jaredhk.com/redirects/common/diversity.html
- [x] https://hub.jaredhk.com/stims.html -> https://hub.jaredhk.com/redirects/common/stims.html
- [x] https://hub.jaredhk.com/docs/index.html -> https://hub.jaredhk.com/docs.html

**Comment by jaredhasenklein** [comment]
Pickers don't actually need fixing. Checking em off

**Comment by jaredhasenklein** [comment]
As of 6bbfe77, all redirects that can happen from here have been created. The rest of the redirects have to happen with the domain registrar for all those subdomains. Fun!

**Comment by jaredhasenklein** [comment]
DONE
